<option value="Ext.form.TextField"    <?=(isset($renderList)&&isset($renderList[$dataRenderIndex])&&$renderList[$dataRenderIndex]=="Ext.form.TextField"?"selected":'')?>>TextField</option>
<option value="Ext.form.NumberField"  <?=(isset($renderList)&&isset($renderList[$dataRenderIndex])&&$renderList[$dataRenderIndex]=="Ext.form.NumberField"?"selected":'')?>>NumberField</option>
<option value="Ext.form.ComboBox"     <?=(isset($renderList)&&isset($renderList[$dataRenderIndex])&&$renderList[$dataRenderIndex]=="Ext.form.ComboBox"?"selected":'')?>>ComboBox</option>
<option value="Ext.form.Checkbox"     <?=(isset($renderList)&&isset($renderList[$dataRenderIndex])&&$renderList[$dataRenderIndex]=="Ext.form.Checkbox"?"selected":'')?>>Checkbox</option>
<option value="Ext.form.Radio"        <?=(isset($renderList)&&isset($renderList[$dataRenderIndex])&&$renderList[$dataRenderIndex]=="Ext.form.Radio"?"selected":'')?>>RadioField</option>
<option value="Ext.ux.form.XCheckbox" <?=(isset($renderList)&&isset($renderList[$dataRenderIndex])&&$renderList[$dataRenderIndex]=="Ext.ux.form.XCheckbox"?"selected":'')?>>XCheckbox</option>
<option value="Ext.form.DateField"    <?=(isset($renderList)&&isset($renderList[$dataRenderIndex])&&$renderList[$dataRenderIndex]=="Ext.form.DateField"?"selected":'')?>>DateField</option>
<option value="Ext.form.TextArea"     <?=(isset($renderList)&&isset($renderList[$dataRenderIndex])&&$renderList[$dataRenderIndex]=="Ext.form.TextArea"?"selected":'')?>>TextArea</option>
<option value="Ext.form.HtmlEditor"   <?=(isset($renderList)&&isset($renderList[$dataRenderIndex])&&$renderList[$dataRenderIndex]=="Ext.form.HtmlEditor"?"selected":'')?>>HtmlEditor</option>
<option value="Ext.form.TimeField"    <?=(isset($renderList)&&isset($renderList[$dataRenderIndex])&&$renderList[$dataRenderIndex]=="Ext.form.TimeField"?"selected":'')?>>TimeField</option>
